# Generated by Django 4.2.25 on 2025-11-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qeyd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=200)),
                ('mezmun', models.TextField()),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
